name: Release

on:
  push:
    tags:
      - "v[0-9]+.*"

jobs:
  prepare:
    name: Create draft release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          gh release create ${{ github.ref_name }} 
          --title "${{ github.ref_name }}"
          --draft 
          --prerelease
          --generate-notes

  build-mac:
    needs: prepare
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          target: ${{ matrix.target }}

      - name: Install Mac SDK
        run: |
          curl -L "https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.9.sdk.tar.xz" | tar -J -x -C /opt
          curl -L "https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz" | tar -J -x -C /opt
          echo "SDKROOT=/opt/MacOSX11.3.sdk" >> $GITHUB_ENV

      - name: Install cargo-zigbuild
        run: |
          pip3 install cargo-zigbuild

      - name: Build
        run: cargo zigbuild --target ${{ matrix.target }} --package lovely-mac --release

      - name: Compress tar.gz
        run: |
          cd ./target/${{ matrix.target }}/release/
          tar czfv tcli-${{ matrix.target }}.tar.gz liblovely.dylib "../../../crates/lovely-mac/run_lovely.sh"
          mv "lovely-${{ matrix.target }}.tar.gz" ${{ github.workspace }}
      
      - name: Submit build artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          gh release upload ${{ github.ref_name }} lovely-${{ matrix.target }}.tar.gz
